[package]
name = "engine"
version = "0.1.0"
authors = ["Kostya"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
sfml = "0.15.1"

[patch.crates-io]
sfml-build = { path = "sfml-build" }
